ability_score_weights:
  random:
    3:  1
    4:  1
    5:  1
    6:  1
    7:  1
    8:  1
    9:  1
    10: 1
    11: 1
    12: 1
    13: 1
    14: 1
    15: 1
    16: 1
    17: 1
    18: 1
    19: 1
    20: 2
  weighted:
    3:  1
    4:  3
    5:  1
    6:  3
    7:  1
    8:  3
    9:  1
    10: 3
    11: 1
    12: 3
    13: 1
    14: 3
    15: 1
    16: 3
    17: 1
    18: 3
    19: 1
    20: 3
  smart:
    3:  1
    4:  2
    5:  2
    6:  5
    7:  3
    8:  5
    9:  3
    10: 4
    11: 2
    12: 4
    13: 2
    14: 6
    15: 4
    16: 10
    17: 8
    18: 16
    19: 14
    20: 20
