data_sources_allowed:
  default: all
  race: volos_guide_to_monsters
generation_style:
  default: smart
  race: weighted
  class: smart
feats: sometimes # always, sometimes, or never
log_level: info # debug